/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
	| 'Pacific/Midway'
	| 'Pacific/Niue'
	| 'Pacific/Honolulu'
	| 'Pacific/Rarotonga'
	| 'America/Anchorage'
	| 'Pacific/Gambier'
	| 'America/Los_Angeles'
	| 'America/Tijuana'
	| 'America/Denver'
	| 'America/Phoenix'
	| 'America/Chicago'
	| 'America/Guatemala'
	| 'America/New_York'
	| 'America/Bogota'
	| 'America/Caracas'
	| 'America/Santiago'
	| 'America/Buenos_Aires'
	| 'America/Sao_Paulo'
	| 'Atlantic/South_Georgia'
	| 'Atlantic/Azores'
	| 'Atlantic/Cape_Verde'
	| 'Europe/London'
	| 'Europe/Berlin'
	| 'Africa/Lagos'
	| 'Europe/Athens'
	| 'Africa/Cairo'
	| 'Europe/Moscow'
	| 'Asia/Riyadh'
	| 'Asia/Dubai'
	| 'Asia/Baku'
	| 'Asia/Karachi'
	| 'Asia/Tashkent'
	| 'Asia/Calcutta'
	| 'Asia/Dhaka'
	| 'Asia/Almaty'
	| 'Asia/Jakarta'
	| 'Asia/Bangkok'
	| 'Asia/Shanghai'
	| 'Asia/Singapore'
	| 'Asia/Tokyo'
	| 'Asia/Seoul'
	| 'Australia/Brisbane'
	| 'Australia/Sydney'
	| 'Pacific/Guam'
	| 'Pacific/Noumea'
	| 'Pacific/Auckland'
	| 'Pacific/Fiji';

export interface Config {
	auth: {
		users: UserAuthOperations;
	};
	blocks: {};
	collections: {
		persona: Persona;
		media: Media;
		file: File;
		location: Location;
		topic: Topic;
		activity: Activity;
		enrollment: Enrollment;
		form: Form;
		'form-submission': FormSubmission;
		video: Video;
		newsletter: Newsletter;
		'newsletter-subscriptions': NewsletterSubscription;
		users: User;
		search: Search;
		'payload-kv': PayloadKv;
		'payload-jobs': PayloadJob;
		'payload-locked-documents': PayloadLockedDocument;
		'payload-preferences': PayloadPreference;
		'payload-migrations': PayloadMigration;
	};
	collectionsJoins: {
		persona: {
			user: 'users';
		};
		activity: {
			enrollments: 'enrollment';
		};
		video: {
			activities: 'activity';
		};
	};
	collectionsSelect: {
		persona: PersonaSelect<false> | PersonaSelect<true>;
		media: MediaSelect<false> | MediaSelect<true>;
		file: FileSelect<false> | FileSelect<true>;
		location: LocationSelect<false> | LocationSelect<true>;
		topic: TopicSelect<false> | TopicSelect<true>;
		activity: ActivitySelect<false> | ActivitySelect<true>;
		enrollment: EnrollmentSelect<false> | EnrollmentSelect<true>;
		form: FormSelect<false> | FormSelect<true>;
		'form-submission': FormSubmissionSelect<false> | FormSubmissionSelect<true>;
		video: VideoSelect<false> | VideoSelect<true>;
		newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
		'newsletter-subscriptions':
			| NewsletterSubscriptionsSelect<false>
			| NewsletterSubscriptionsSelect<true>;
		users: UsersSelect<false> | UsersSelect<true>;
		search: SearchSelect<false> | SearchSelect<true>;
		'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
		'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
		'payload-locked-documents':
			| PayloadLockedDocumentsSelect<false>
			| PayloadLockedDocumentsSelect<true>;
		'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
		'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
	};
	db: {
		defaultIDType: string;
	};
	globals: {
		about: About;
	};
	globalsSelect: {
		about: AboutSelect<false> | AboutSelect<true>;
	};
	locale: 'it' | 'en';
	user: User & {
		collection: 'users';
	};
	jobs: {
		tasks: {
			updateActivityStatus: TaskUpdateActivityStatus;
			'send-newsletter': TaskSendNewsletter;
			schedulePublish: TaskSchedulePublish;
			inline: {
				input: unknown;
				output: unknown;
			};
		};
		workflows: unknown;
	};
}
export interface UserAuthOperations {
	forgotPassword: {
		email: string;
		password: string;
	};
	login: {
		email: string;
		password: string;
	};
	registerFirstUser: {
		email: string;
		password: string;
	};
	unlock: {
		email: string;
		password: string;
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persona".
 */
export interface Persona {
	id: string;
	/**
	 * If true, the user's profile will be visible to the public.
	 */
	privacySettings?: boolean | null;
	name: string;
	email?: string | null;
	avatar?: (string | null) | Media;
	bio?: string | null;
	/**
	 * The skills of the user.
	 */
	skills?: (string | Topic)[] | null;
	/**
	 * Social links
	 */
	links?:
		| {
				url?: string | null;
				label?: string | null;
				id?: string | null;
		  }[]
		| null;
	user?: {
		docs?: (string | User)[];
		hasNextPage?: boolean;
		totalDocs?: number;
	};
	slug?: string | null;
	slugLock?: boolean | null;
	meta?: {
		title?: string | null;
		/**
		 * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
		 */
		image?: (string | null) | Media;
		description?: string | null;
	};
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
	id: string;
	alt: string;
	blurHash?: string | null;
	prefix?: string | null;
	updatedAt: string;
	createdAt: string;
	url?: string | null;
	thumbnailURL?: string | null;
	filename?: string | null;
	mimeType?: string | null;
	filesize?: number | null;
	width?: number | null;
	height?: number | null;
	focalX?: number | null;
	focalY?: number | null;
	sizes?: {
		'thumbnail-square'?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
		thumbnail?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
		medium?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
		large?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
		xlarge?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
		og?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic".
 */
export interface Topic {
	id: string;
	name: string;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
	id: string;
	/**
	 * The phone number of the user.
	 */
	phone?: string | null;
	/**
	 * The roles of the user.
	 */
	roles?: ('user' | 'editor' | 'superadmin')[] | null;
	persona?: (string | null) | Persona;
	sub?: string | null;
	stripeID?: string | null;
	skipSync?: boolean | null;
	updatedAt: string;
	createdAt: string;
	email: string;
	resetPasswordToken?: string | null;
	resetPasswordExpiration?: string | null;
	salt?: string | null;
	hash?: string | null;
	_verified?: boolean | null;
	_verificationToken?: string | null;
	loginAttempts?: number | null;
	lockUntil?: string | null;
	sessions?:
		| {
				id: string;
				createdAt?: string | null;
				expiresAt: string;
		  }[]
		| null;
	password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "file".
 */
export interface File {
	id: string;
	title?: string | null;
	user?: (string | null) | User;
	prefix?: string | null;
	updatedAt: string;
	createdAt: string;
	url?: string | null;
	thumbnailURL?: string | null;
	filename?: string | null;
	mimeType?: string | null;
	filesize?: number | null;
	width?: number | null;
	height?: number | null;
	focalX?: number | null;
	focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location".
 */
export interface Location {
	id: string;
	name: string;
	image?: (string | null) | Media;
	address?: string | null;
	mapUrl?: string | null;
	phone?: string | null;
	email?: string | null;
	website?: string | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity".
 */
export interface Activity {
	id: string;
	name: string;
	shortDescription: string;
	description: {
		root: {
			type: string;
			children: {
				type: any;
				version: number;
				[k: string]: unknown;
			}[];
			direction: ('ltr' | 'rtl') | null;
			format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
			indent: number;
			version: number;
		};
		[k: string]: unknown;
	};
	relatedPersonas?:
		| {
				role?: ('docente' | 'speaker' | 'assistente' | 'tutor') | null;
				persona?: (string | null) | Persona;
				id?: string | null;
		  }[]
		| null;
	program?: {
		/**
		 * Where will the activity be held?
		 */
		where?: ('online' | 'irl') | null;
		onlineLink?: string | null;
		location?: (string | null) | Location;
		/**
		 * List of appointments
		 */
		appointments?:
			| {
					start: string;
					end: string;
					location?: (string | null) | Location;
					onlineLink?: string | null;
					shortDescription?: string | null;
					id?: string | null;
			  }[]
			| null;
	};
	enrollment?: {
		enrollable?: boolean | null;
		activityStatus?:
			| ('draft' | 'enrolling' | 'enrolled' | 'confirmed' | 'cancelled' | 'archived')
			| null;
		start?: string | null;
		deadline?: string | null;
		minParticipants?: number | null;
		maxParticipants?: number | null;
		requirePayment?: boolean | null;
		price?: number | null;
		/**
		 * Enable an introduction section to the form
		 */
		enableIntro?: boolean | null;
		introContent?: {
			root: {
				type: string;
				children: {
					type: any;
					version: number;
					[k: string]: unknown;
				}[];
				direction: ('ltr' | 'rtl') | null;
				format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
				indent: number;
				version: number;
			};
			[k: string]: unknown;
		} | null;
		form?: (string | null) | Form;
	};
	enrollments?: {
		docs?: (string | Enrollment)[];
		hasNextPage?: boolean;
		totalDocs?: number;
	};
	meta?: {
		title?: string | null;
		/**
		 * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
		 */
		image?: (string | null) | Media;
		description?: string | null;
	};
	slug?: string | null;
	slugLock?: boolean | null;
	image: string | Media;
	type?: ('event' | 'course' | 'workshop' | 'party' | 'open_call' | 'other') | null;
	topics?: (string | Topic)[] | null;
	video?: (string | null) | Video;
	year_month?: string[] | null;
	updatedAt: string;
	createdAt: string;
	_status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form".
 */
export interface Form {
	id: string;
	name: string;
	description?: string | null;
	fields?:
		| (
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						defaultValue?: string | null;
						options?:
							| {
									label: string;
									value: string;
									description?: string | null;
									id?: string | null;
							  }[]
							| null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'select';
				  }
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						required?: boolean | null;
						defaultValue?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'checkbox';
				  }
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						defaultValue?: string | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'text';
				  }
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						defaultValue?: string | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'textarea';
				  }
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'email';
				  }
				| {
						message?: {
							root: {
								type: string;
								children: {
									type: any;
									version: number;
									[k: string]: unknown;
								}[];
								direction: ('ltr' | 'rtl') | null;
								format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
								indent: number;
								version: number;
							};
							[k: string]: unknown;
						} | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'message';
				  }
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						defaultValue?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'number';
				  }
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'country';
				  }
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'state';
				  }
				| {
						name: string;
						label?: string | null;
						description?: string | null;
						width?: number | null;
						maxFiles?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: 'file';
				  }
		  )[]
		| null;
	submitButtonLabel?: string | null;
	/**
	 * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}.
	 */
	emails?:
		| {
				emailTo?: string | null;
				cc?: string | null;
				bcc?: string | null;
				replyTo?: string | null;
				emailFrom?: string | null;
				subject: string;
				/**
				 * Enter the message that should be sent in this email.
				 */
				message?: {
					root: {
						type: string;
						children: {
							type: any;
							version: number;
							[k: string]: unknown;
						}[];
						direction: ('ltr' | 'rtl') | null;
						format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
						indent: number;
						version: number;
					};
					[k: string]: unknown;
				} | null;
				id?: string | null;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollment".
 */
export interface Enrollment {
	id: string;
	activity: string | Activity;
	user: string | User;
	formSubmission: string | FormSubmission;
	paymentId?: string | null;
	status?:
		| (
				| 'draft'
				| 'pending_payment'
				| 'payment_failed'
				| 'awaiting_admin_confirmation'
				| 'confirmed'
				| 'cancelled'
				| 'completed'
		  )
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submission".
 */
export interface FormSubmission {
	id: string;
	form: string | Form;
	submissionData?:
		| {
				field: string;
				value: string;
				id?: string | null;
		  }[]
		| null;
	user?: (string | null) | User;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video".
 */
export interface Video {
	id: string;
	title: string;
	description?: string | null;
	activities?: {
		docs?: (string | Activity)[];
		hasNextPage?: boolean;
		totalDocs?: number;
	};
	thumbnail?: (string | null) | Media;
	prefix?: string | null;
	updatedAt: string;
	createdAt: string;
	url?: string | null;
	thumbnailURL?: string | null;
	filename?: string | null;
	mimeType?: string | null;
	filesize?: number | null;
	width?: number | null;
	height?: number | null;
	focalX?: number | null;
	focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
	id: string;
	title: string;
	description?: string | null;
	month: number;
	activities?: (string | Activity)[] | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions".
 */
export interface NewsletterSubscription {
	id: string;
	email: string;
	updatedAt: string;
	createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
	id: string;
	title?: string | null;
	priority?: number | null;
	doc: {
		relationTo: 'activity';
		value: string | Activity;
	};
	slug?: string | null;
	meta?: {
		title?: string | null;
		description?: string | null;
		type?: string | null;
		image?: (string | null) | Media;
		startDate?: string | null;
		/**
		 * Format: YYYY-MM for efficient querying
		 */
		yearMonth?: string | null;
	};
	topics?:
		| {
				relationTo?: string | null;
				id?: string | null;
				name?: string | null;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
	id: string;
	key: string;
	data:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
	id: string;
	/**
	 * Input data provided to the job
	 */
	input?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	taskStatus?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	completedAt?: string | null;
	totalTried?: number | null;
	/**
	 * If hasError is true this job will not be retried
	 */
	hasError?: boolean | null;
	/**
	 * If hasError is true, this is the error that caused it
	 */
	error?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	/**
	 * Task execution log
	 */
	log?:
		| {
				executedAt: string;
				completedAt: string;
				taskSlug: 'inline' | 'updateActivityStatus' | 'send-newsletter' | 'schedulePublish';
				taskID: string;
				input?:
					| {
							[k: string]: unknown;
					  }
					| unknown[]
					| string
					| number
					| boolean
					| null;
				output?:
					| {
							[k: string]: unknown;
					  }
					| unknown[]
					| string
					| number
					| boolean
					| null;
				state: 'failed' | 'succeeded';
				error?:
					| {
							[k: string]: unknown;
					  }
					| unknown[]
					| string
					| number
					| boolean
					| null;
				id?: string | null;
		  }[]
		| null;
	taskSlug?: ('inline' | 'updateActivityStatus' | 'send-newsletter' | 'schedulePublish') | null;
	queue?: string | null;
	waitUntil?: string | null;
	processing?: boolean | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
	id: string;
	document?:
		| ({
				relationTo: 'persona';
				value: string | Persona;
		  } | null)
		| ({
				relationTo: 'media';
				value: string | Media;
		  } | null)
		| ({
				relationTo: 'file';
				value: string | File;
		  } | null)
		| ({
				relationTo: 'location';
				value: string | Location;
		  } | null)
		| ({
				relationTo: 'topic';
				value: string | Topic;
		  } | null)
		| ({
				relationTo: 'activity';
				value: string | Activity;
		  } | null)
		| ({
				relationTo: 'enrollment';
				value: string | Enrollment;
		  } | null)
		| ({
				relationTo: 'form';
				value: string | Form;
		  } | null)
		| ({
				relationTo: 'form-submission';
				value: string | FormSubmission;
		  } | null)
		| ({
				relationTo: 'video';
				value: string | Video;
		  } | null)
		| ({
				relationTo: 'newsletter';
				value: string | Newsletter;
		  } | null)
		| ({
				relationTo: 'newsletter-subscriptions';
				value: string | NewsletterSubscription;
		  } | null)
		| ({
				relationTo: 'users';
				value: string | User;
		  } | null)
		| ({
				relationTo: 'search';
				value: string | Search;
		  } | null);
	globalSlug?: string | null;
	user: {
		relationTo: 'users';
		value: string | User;
	};
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
	id: string;
	user: {
		relationTo: 'users';
		value: string | User;
	};
	key?: string | null;
	value?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
	id: string;
	name?: string | null;
	batch?: number | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persona_select".
 */
export interface PersonaSelect<T extends boolean = true> {
	privacySettings?: T;
	name?: T;
	email?: T;
	avatar?: T;
	bio?: T;
	skills?: T;
	links?:
		| T
		| {
				url?: T;
				label?: T;
				id?: T;
		  };
	user?: T;
	slug?: T;
	slugLock?: T;
	meta?:
		| T
		| {
				title?: T;
				image?: T;
				description?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
	alt?: T;
	blurHash?: T;
	prefix?: T;
	updatedAt?: T;
	createdAt?: T;
	url?: T;
	thumbnailURL?: T;
	filename?: T;
	mimeType?: T;
	filesize?: T;
	width?: T;
	height?: T;
	focalX?: T;
	focalY?: T;
	sizes?:
		| T
		| {
				'thumbnail-square'?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
				thumbnail?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
				medium?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
				large?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
				xlarge?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
				og?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
		  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "file_select".
 */
export interface FileSelect<T extends boolean = true> {
	title?: T;
	user?: T;
	prefix?: T;
	updatedAt?: T;
	createdAt?: T;
	url?: T;
	thumbnailURL?: T;
	filename?: T;
	mimeType?: T;
	filesize?: T;
	width?: T;
	height?: T;
	focalX?: T;
	focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location_select".
 */
export interface LocationSelect<T extends boolean = true> {
	name?: T;
	image?: T;
	address?: T;
	mapUrl?: T;
	phone?: T;
	email?: T;
	website?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic_select".
 */
export interface TopicSelect<T extends boolean = true> {
	name?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_select".
 */
export interface ActivitySelect<T extends boolean = true> {
	name?: T;
	shortDescription?: T;
	description?: T;
	relatedPersonas?:
		| T
		| {
				role?: T;
				persona?: T;
				id?: T;
		  };
	program?:
		| T
		| {
				where?: T;
				onlineLink?: T;
				location?: T;
				appointments?:
					| T
					| {
							start?: T;
							end?: T;
							location?: T;
							onlineLink?: T;
							shortDescription?: T;
							id?: T;
					  };
		  };
	enrollment?:
		| T
		| {
				enrollable?: T;
				activityStatus?: T;
				start?: T;
				deadline?: T;
				minParticipants?: T;
				maxParticipants?: T;
				requirePayment?: T;
				price?: T;
				enableIntro?: T;
				introContent?: T;
				form?: T;
		  };
	enrollments?: T;
	meta?:
		| T
		| {
				title?: T;
				image?: T;
				description?: T;
		  };
	slug?: T;
	slugLock?: T;
	image?: T;
	type?: T;
	topics?: T;
	video?: T;
	year_month?: T;
	updatedAt?: T;
	createdAt?: T;
	_status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollment_select".
 */
export interface EnrollmentSelect<T extends boolean = true> {
	activity?: T;
	user?: T;
	formSubmission?: T;
	paymentId?: T;
	status?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form_select".
 */
export interface FormSelect<T extends boolean = true> {
	name?: T;
	description?: T;
	fields?:
		| T
		| {
				select?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							defaultValue?: T;
							options?:
								| T
								| {
										label?: T;
										value?: T;
										description?: T;
										id?: T;
								  };
							required?: T;
							id?: T;
							blockName?: T;
					  };
				checkbox?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							required?: T;
							defaultValue?: T;
							id?: T;
							blockName?: T;
					  };
				text?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							defaultValue?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				textarea?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							defaultValue?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				email?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				message?:
					| T
					| {
							message?: T;
							id?: T;
							blockName?: T;
					  };
				number?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							defaultValue?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				country?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				state?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				file?:
					| T
					| {
							name?: T;
							label?: T;
							description?: T;
							width?: T;
							maxFiles?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
		  };
	submitButtonLabel?: T;
	emails?:
		| T
		| {
				emailTo?: T;
				cc?: T;
				bcc?: T;
				replyTo?: T;
				emailFrom?: T;
				subject?: T;
				message?: T;
				id?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submission_select".
 */
export interface FormSubmissionSelect<T extends boolean = true> {
	form?: T;
	submissionData?:
		| T
		| {
				field?: T;
				value?: T;
				id?: T;
		  };
	user?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video_select".
 */
export interface VideoSelect<T extends boolean = true> {
	title?: T;
	description?: T;
	activities?: T;
	thumbnail?: T;
	prefix?: T;
	updatedAt?: T;
	createdAt?: T;
	url?: T;
	thumbnailURL?: T;
	filename?: T;
	mimeType?: T;
	filesize?: T;
	width?: T;
	height?: T;
	focalX?: T;
	focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
	title?: T;
	description?: T;
	month?: T;
	activities?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions_select".
 */
export interface NewsletterSubscriptionsSelect<T extends boolean = true> {
	email?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
	phone?: T;
	roles?: T;
	persona?: T;
	sub?: T;
	stripeID?: T;
	skipSync?: T;
	updatedAt?: T;
	createdAt?: T;
	email?: T;
	resetPasswordToken?: T;
	resetPasswordExpiration?: T;
	salt?: T;
	hash?: T;
	_verified?: T;
	_verificationToken?: T;
	loginAttempts?: T;
	lockUntil?: T;
	sessions?:
		| T
		| {
				id?: T;
				createdAt?: T;
				expiresAt?: T;
		  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
	title?: T;
	priority?: T;
	doc?: T;
	slug?: T;
	meta?:
		| T
		| {
				title?: T;
				description?: T;
				type?: T;
				image?: T;
				startDate?: T;
				yearMonth?: T;
		  };
	topics?:
		| T
		| {
				relationTo?: T;
				id?: T;
				name?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
	key?: T;
	data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
	input?: T;
	taskStatus?: T;
	completedAt?: T;
	totalTried?: T;
	hasError?: T;
	error?: T;
	log?:
		| T
		| {
				executedAt?: T;
				completedAt?: T;
				taskSlug?: T;
				taskID?: T;
				input?: T;
				output?: T;
				state?: T;
				error?: T;
				id?: T;
		  };
	taskSlug?: T;
	queue?: T;
	waitUntil?: T;
	processing?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
	document?: T;
	globalSlug?: T;
	user?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
	user?: T;
	key?: T;
	value?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
	name?: T;
	batch?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
	id: string;
	title?: string | null;
	description?: {
		root: {
			type: string;
			children: {
				type: any;
				version: number;
				[k: string]: unknown;
			}[];
			direction: ('ltr' | 'rtl') | null;
			format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
			indent: number;
			version: number;
		};
		[k: string]: unknown;
	} | null;
	updatedAt?: string | null;
	createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
	title?: T;
	description?: T;
	updatedAt?: T;
	createdAt?: T;
	globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUpdateActivityStatus".
 */
export interface TaskUpdateActivityStatus {
	input: {
		activityID: string;
		status: 'draft' | 'confirmed' | 'cancelled' | 'enrolling' | 'enrolled' | 'archived';
	};
	output: {
		activityID: string;
		status: string;
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-newsletter".
 */
export interface TaskSendNewsletter {
	input: {
		newsletter_id: string;
	};
	output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
	input: {
		type?: ('publish' | 'unpublish') | null;
		locale?: string | null;
		doc?: {
			relationTo: 'activity';
			value: string | Activity;
		} | null;
		global?: string | null;
		user?: (string | null) | User;
	};
	output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
	[k: string]: unknown;
}
